org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

archives_base_name=travelled_tracks

# https://semver.org/
mod_version=2.0.0

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47.4,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=travelled_tracks
mod_name=Travelled Tracks
mod_license=MIT
mod_group_id=com.blockninja
mod_authors=Blockninja124
mod_description=Adds compatiblity between Trackwork and TRMT (The Roads More Travelled)

vs2_mc_version=120
#vs2_version=2.5.0-beta.1+a81efdff02
#vs_core_version=1.1.0+cf7b0d3c5b
vs2_version=2.4.11+c1e5b68ef8
vs_core_version=1.1.0+cf208d8b56

# Makes MDG use parchment
neoForge.parchment.minecraftVersion=1.20.1
neoForge.parchment.mappingsVersion=2023.09.03