modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/blockninja124/travelled_tracks/issues"
license = "MIT"

[[mods]]
modId = "travelled_tracks"
version = "${mod_version}"
displayName = "Travelled Tracks"
authors = "Brickyboy"
description = '''
Adds compatiblity between Trackwork and TRMT (The Roads More Travelled)
'''
credits = "Crazywoddman - the car build in the logo"
logoFile = "logo.png"

[[dependencies.travelled_tracks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.travelled_tracks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.travelled_tracks]]
modId = "trackwork"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.travelled_tracks]]
modId = "trmt"
mandatory = true
versionRange = "[0.4-1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.travelled_tracks]]
modId = "connectormod"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"