architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modApi("org.valkyrienskies:valkyrienskies-120-common:${rootProject.vs2_version}") {
        exclude group: "com.simibubi"
    }
    implementation("org.valkyrienskies.core:api:${rootProject.vs_core_version}") {
        exclude group: 'org.joml', module: ''
    }
    implementation("org.valkyrienskies.core:impl:${rootProject.vs_core_version}") {
        exclude group: 'org.joml', module: ''
    }
    implementation("org.valkyrienskies.core:internal:${rootProject.vs_core_version}") {
        exclude group: 'org.joml', module: ''
    }

    implementation("maven.modrinth:create:8amzvn9x")

    implementation("org.joml:joml-primitives:1.10.0")
    implementation("org.joml:joml:1.10.4")
}
